- name: Configure Docker and Monitoring on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update yum packages
      yum:
        name: '*'
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add EC2 user to Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull Docker Image
      command: docker pull shoaibpathan/banking-project-demo:3.0

    - name: Deploy Docker Container
      command: docker run -itd -p 8080:8081 shoaibpathan/banking-project-demo:3.0

    - name: Install dependencies for monitoring
      yum:
        name: [wget, tar, unzip]
        state: present

    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v3.3.0-rc.0/prometheus-3.3.0-rc.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Configure Prometheus
      copy:
        dest: /opt/prometheus-linux-amd64/prometheus.yml
        content: |
          global:
            scrape_interval: 5s
          scrape_configs:
            - job_name: 'node_exporter'
              static_configs:
                - targets: ['localhost:9100']

    - name: Start Prometheus
      command: nohup /opt/prometheus-linux-amd64/prometheus --config.file=/opt/prometheus-linux-amd64/prometheus.yml &

    - name: Download Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/latest/download/node_exporter-linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Start Node Exporter
      command: nohup /opt/node_exporter-linux-amd64/node_exporter &

    - name: Install Grafana
      yum:
        name: grafana
        state: present

    - name: Start Grafana Service
      service:
        name: grafana-server
        state: started
        enabled: yes

    - name: Allow firewall rules for monitoring
      command: firewall-cmd --permanent --add-port=3000/tcp && firewall-cmd --permanent --add-port=9090/tcp && firewall-cmd --permanent --add-port=9100/tcp && firewall-cmd --reload
