- name: Configure Docker and Monitoring Tools on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update yum packages
      yum:
        name: '*'
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add EC2 user to Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull Docker Image
      command: docker pull shoaibpathan/banking-project-demo:3.0

    - name: Deploy Docker Container
      command: docker run -itd -p 8080:8081 shoaibpathan/banking-project-demo:3.0

    # ---- FIX: Ensure directory exists before extracting Prometheus ----
    - name: Create Prometheus directory
      file:
        path: /opt/prometheus-linux-amd64
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v3.3.0-rc.0/prometheus-3.3.0-rc.0.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/prometheus-linux-amd64
        remote_src: yes

    - name: Start Prometheus
      command: "nohup /opt/prometheus-linux-amd64/prometheus --config.file=/opt/prometheus-linux-amd64/prometheus.yml &"


